# Generated by Django 3.1.7 on 2021-06-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=60, verbose_name='Status:')),
                ('motivo', models.CharField(blank=True, max_length=60, verbose_name='Motivo:')),
                ('data_atual', models.CharField(blank=True, max_length=60, verbose_name='Data Atual:')),
                ('afetado', models.CharField(blank=True, max_length=60, verbose_name='Locais Afetados:')),
                ('retorno', models.CharField(blank=True, max_length=60, verbose_name='Retorno:')),
            ],
        ),
    ]
