# Generated by Django 3.1.7 on 2021-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_objeto', models.CharField(blank=True, max_length=60, verbose_name='Nome:')),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição:')),
                ('preço', models.CharField(blank=True, max_length=60, verbose_name='Preço:')),
                ('disponibilidade', models.CharField(blank=True, max_length=60, verbose_name='Disponibilidade:')),
                ('foto', models.ImageField(default='/static/no_image.png', upload_to='media/', verbose_name='Foto')),
            ],
        ),
    ]
