# Generated by Django 3.1.7 on 2021-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ocorrencia', models.CharField(blank=True, max_length=100, verbose_name='Nome da Ocorrencia:')),
                ('motivo_ocorrencia', models.CharField(blank=True, max_length=200, verbose_name='Motivo da Ocorrencia:')),
                ('local_ocorrencia', models.CharField(blank=True, max_length=60, verbose_name='Local da Ocorrencia:')),
                ('nome_cliente', models.CharField(blank=True, max_length=60, verbose_name='Nome do Cliente:')),
            ],
        ),
    ]
